#!/usr/bin/env bash

echo
echo "  cURLiQ  CREATE BROKER v.0.0.0"
echo

echo "Enter the name of the broker to be created.  Broker names must start"
echo "with a letter which may be followed by up to 14 letters, numerals, or"
echo "underscores."
echo
echo "Enter Ctrl-C to cancel."
echo

while [ -z "${name}" ]
do
    echo -n "Name: "
    read name
done

echo
echo

name=$(echo $name | tr [a-z] [A-Z])

cat broker.sql | sed "s/@@NAME@@/${name}/g" | sqlite3 "$name"

if [ 0 -eq $? ]
then
    echo
    echo "  Broker $name was successfully created."
    echo
    exit 0
else
    echo "  Broker $name creation failed.">&2 ; exit 2 
fi

