#!/usr/bin/env bash

# 
#  Copyright (C) 2019 Matthew Alton
# 
#  This file is part of cURLiQ.
# 
#  cURLiQ is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  cURLiQ is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with cURLiQ.  If not, see <http://www.gnu.org/licenses/>.
# 

psql <<EOF

DROP TABLE IF EXISTS system CASCADE;
DROP TABLE IF EXISTS queue CASCADE;
DROP TABLE IF EXISTS http_target CASCADE;
DROP TABLE IF EXISTS has_http_target CASCADE;
DROP TABLE IF EXISTS has_target CASCADE;
DROP TABLE IF EXISTS target_group CASCADE;
DROP TABLE IF EXISTS contains_target CASCADE;
DROP TABLE IF EXISTS queue_group CASCADE;
DROP TABLE IF EXISTS contains_queue CASCADE;
DROP TABLE IF EXISTS dict_target CASCADE;
DROP TABLE IF EXISTS has_dict_target CASCADE;
DROP TABLE IF EXISTS file_target CASCADE;
DROP TABLE IF EXISTS has_file_target CASCADE;
DROP TABLE IF EXISTS ftp_target CASCADE;
DROP TABLE IF EXISTS has_ftp_target CASCADE;
DROP TABLE IF EXISTS ftps_target CASCADE;
DROP TABLE IF EXISTS has_ftps_target CASCADE;
DROP TABLE IF EXISTS gopher_target CASCADE;
DROP TABLE IF EXISTS has_gopher_target CASCADE;
DROP TABLE IF EXISTS http_target CASCADE;
DROP TABLE IF EXISTS has_http_target CASCADE;
DROP TABLE IF EXISTS https_target CASCADE;
DROP TABLE IF EXISTS has_https_target CASCADE;
DROP TABLE IF EXISTS imap_target CASCADE;
DROP TABLE IF EXISTS has_imap_target CASCADE;
DROP TABLE IF EXISTS imaps_target CASCADE;
DROP TABLE IF EXISTS has_imaps_target CASCADE;
DROP TABLE IF EXISTS ldap_target CASCADE;
DROP TABLE IF EXISTS has_ldap_target CASCADE;
DROP TABLE IF EXISTS ldaps_target CASCADE;
DROP TABLE IF EXISTS has_ldaps_target CASCADE;
DROP TABLE IF EXISTS pop3_target CASCADE;
DROP TABLE IF EXISTS has_pop3_target CASCADE;
DROP TABLE IF EXISTS pop3s_target CASCADE;
DROP TABLE IF EXISTS has_pop3s_target CASCADE;
DROP TABLE IF EXISTS rtmp_target CASCADE;
DROP TABLE IF EXISTS has_rtmp_target CASCADE;
DROP TABLE IF EXISTS rtsp_target CASCADE;
DROP TABLE IF EXISTS has_rtsp_target CASCADE;
DROP TABLE IF EXISTS scp_target CASCADE;
DROP TABLE IF EXISTS has_scp_target CASCADE;
DROP TABLE IF EXISTS sftp_target CASCADE;
DROP TABLE IF EXISTS has_sftp_target CASCADE;
DROP TABLE IF EXISTS smb_target CASCADE;
DROP TABLE IF EXISTS has_smb_target CASCADE;
DROP TABLE IF EXISTS smbs_target CASCADE;
DROP TABLE IF EXISTS has_smbs_target CASCADE;
DROP TABLE IF EXISTS smtp_target CASCADE;
DROP TABLE IF EXISTS has_smtp_target CASCADE;
DROP TABLE IF EXISTS smtps_target CASCADE;
DROP TABLE IF EXISTS has_smtps_target CASCADE;
DROP TABLE IF EXISTS target CASCADE;
DROP TABLE IF EXISTS has_target CASCADE;
DROP TABLE IF EXISTS telnet_target CASCADE;
DROP TABLE IF EXISTS has_telnet_target CASCADE;
DROP TABLE IF EXISTS tftp_target CASCADE;
DROP TABLE IF EXISTS has_tftp_target CASCADE;

EOF
